### PR TITLE
Add global shared context map

### PR DESCRIPTION
**Pull request by matthauck**
Allows us to do things like synchronize between concurrent jobs

### CODE REVIEW

**Comment by briangreenery** [comment]
So all of the tasks run for a certain build will share the same shared_context, and that's okay for them all to access because the worker is single-threaded? Or like it's python so there's a GIL? Orr something? It looks all very sensible in this diff though.

**Comment by matthauck** [comment]
This would allow all tasks across the entire jenkins instance to have the same shared_context, not just across a particular build. This would allow a particular job to store a mutex, for example, under some key on that map to synchronize access to a particular part of a job across multiple concurrent runs.

**Comment by briangreenery** [comment]
Is there a race there if two builds both try to store the same key into the map? I don't really know.

**Comment by matthauck** [comment]
hmm. yeah, there could be a race there. maybe it should use ConcurrentHashMap...

**Pull request merged**
